//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BcuEntities : DbContext
    {
        public BcuEntities()
            : base("name=BcuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attachmentSet> attachmentSet { get; set; }
        public DbSet<collegeSet> collegeSet { get; set; }
        public DbSet<contactSet> contactSet { get; set; }
        public DbSet<cooperationSet> cooperationSet { get; set; }
        public DbSet<courseSet> courseSet { get; set; }
        public DbSet<folderSet> folderSet { get; set; }
        public DbSet<newsSet> newsSet { get; set; }
    }
}
